In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("inference.csv")

In [3]:
df['predicted'] = df.iloc[:, 2:].idxmax(axis=1)
df['predicted'] = pd.to_numeric(df.predicted)

In [4]:
df

,path,real,0,1,2,3,4,predicted
0,/content/content/dataset/cleannonstratifieddr/...,0,56.80,19.43,22.61,0.00,1.17,0
1,/content/content/dataset/cleannonstratifieddr/...,0,52.15,23.99,19.09,4.77,0.00,0
2,/content/content/dataset/cleannonstratifieddr/...,0,60.65,14.63,18.83,0.00,5.88,0
3,/content/content/dataset/cleannonstratifieddr/...,0,45.06,22.66,26.20,6.08,0.00,0
4,/content/content/dataset/cleannonstratifieddr/...,0,55.08,19.07,24.18,1.68,0.00,0
...,...,...,...,...,...,...,...,...
61504,/content/content/dataset/cleannonstratifieddr/...,4,0.00,3.95,18.14,45.69,32.22,3
61505,/content/content/dataset/cleannonstratifieddr/...,4,28.95,12.27,8.58,0.00,50.20,4
61506,/content/content/dataset/cleannonstratifieddr/...,4,17.66,5.09,0.00,6.57,70.68,4
61507,/content/content/dataset/cleannonstratifieddr/...,4,8.95,0.00,20.90,17.76,52.38,4
61508,/content/content/dataset/cleannonstratifieddr/...,4,0.00,1.66,26.37,36.46,35.50,3

In [7]:
df[df['predicted']==df['real']].iloc[:, 2:].max(axis=1).describe()

count    55545.000000
mean        51.928404
std          5.500501
min         28.040000
25%         49.290000
50%         52.550000
75%         55.290000
max         91.420000
dtype: float64

In [8]:
df[df['predicted']!=df['real']].iloc[:, 2:].max(axis=1).describe()

count    5964.000000
mean       43.367698
std         6.429344
min        26.890000
25%        38.710000
50%        42.720000
75%        47.512500
max        71.850000
dtype: float64

In [9]:
def findMinDiff(arr): 
    arr = sorted(arr, reverse=True) 
    return arr[0] - arr[1]

In [10]:
df['difference'] = df[['0', '1', '2', '3', '4']].apply(findMinDiff, axis=1)

In [11]:
df

,path,real,0,1,2,3,4,predicted,difference
0,/content/content/dataset/cleannonstratifieddr/...,0,56.80,19.43,22.61,0.00,1.17,0,34.19
1,/content/content/dataset/cleannonstratifieddr/...,0,52.15,23.99,19.09,4.77,0.00,0,28.16
2,/content/content/dataset/cleannonstratifieddr/...,0,60.65,14.63,18.83,0.00,5.88,0,41.82
3,/content/content/dataset/cleannonstratifieddr/...,0,45.06,22.66,26.20,6.08,0.00,0,18.86
4,/content/content/dataset/cleannonstratifieddr/...,0,55.08,19.07,24.18,1.68,0.00,0,30.90
...,...,...,...,...,...,...,...,...,...
61504,/content/content/dataset/cleannonstratifieddr/...,4,0.00,3.95,18.14,45.69,32.22,3,13.47
61505,/content/content/dataset/cleannonstratifieddr/...,4,28.95,12.27,8.58,0.00,50.20,4,21.25
61506,/content/content/dataset/cleannonstratifieddr/...,4,17.66,5.09,0.00,6.57,70.68,4,53.02
61507,/content/content/dataset/cleannonstratifieddr/...,4,8.95,0.00,20.90,17.76,52.38,4,31.48
61508,/content/content/dataset/cleannonstratifieddr/...,4,0.00,1.66,26.37,36.46,35.50,3,0.96